<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIfndv2c\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIfndv2c/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIfndv2c.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIfndv2c\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIfndv2c\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ifndv2c',
    'container.build_id' => 'a0a01068',
    'container.build_time' => 1524841598,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIfndv2c');
